Repository BRRAD-IT-Solutions/brrad-quiz-game, pull requests merged in 2025-05, with the labels that each got.

#1 moved files from practice folder
  components/index.html
  components/quiz.html
  components/scripts/functions.js
  components/scripts/sample.js
  components/styles/sample.css
  components/styles/styles.css
  images/Character/IdleHero.gif
  images/Character/attackHero.gif
  images/Character/hurtHero.gif
  images/Character/orc-hurt.gif
  images/Character/orc-idle.gif
  images/Character/orcAttack.gif
  images/Start game screen.jpg
  images/sample.png
  videos/sample.mp4
Labels: good first issue

#3 Health bars place holder no function yet
  components/styles/styles.css
Labels: documentation

#5 Add health bar functions and enhancements to code
  components/quiz.html
  components/scripts/functions.js
  components/styles/styles.css
Labels: enhancement

#8 fix index html
  components/index.html
  components/quiz.html
  components/scripts/functions.js
Labels: duplicate

#13 Added Quest for quiz
  components/index.html
  components/story.html
  components/styles/styles.css
  images/Story.png
  images/icons/ScrollWithQuest.png
  images/icons/questLetter.png
Labels: enhancement

#20 fixing order of qestion and answers
  components/scripts/functions.js
Labels: bug, documentation
